import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";
import { Inter } from "next/font/google";
import StoreProvider from "@/providers/storeProviders";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >   
      <StoreProvider>
        <Header></Header>
         <Toaster position="top-center" reverseOrder={false} />
        {children}
        <Footer/>
      </StoreProvider> 
         
      </body>
    </html>
  );
}
